import { Question, Workbook } from '@/app/_lib/types';

export const Dummy_Workbooks: Workbook[] = [
  {
    id: '1',
    title: '23년도 3월 모의고사 오답 모음',
    description: '화이팅 화이팅',
    emoji: '🤓',
    quantity: 25,
    modifiedAt: new Date('2024-04-15'),
  },
  {
    id: '2',
    title: '과학 문제 모음',
    description: '쎈, 마더텅',
    emoji: '👿',
    quantity: 10,
    modifiedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    title: '23년도 9월차 포엠 수학 재시험',
    description:
      '80점 미만 재시험으로 인해서 집에 가지 못하는 불상사가 발생한 하루이다.',
    emoji: '🤢',
    quantity: 10,
    modifiedAt: new Date('2023-05-31'),
  },
  {
    id: '4',
    title:
      '문제집의 이름을 길게하고 싶은 경우 이런식으로 문제집의 이름을 만들 수 있지않을까?',
    description: '한줄 소개는 이정도로 하자',
    emoji: '💩',
    quantity: 0,
    modifiedAt: new Date('2022-06-07'),
  },
  {
    id: '5',
    title: '23년도 3월 모의고사 오답 모음',
    description: '화이팅 화이팅',
    emoji: '🤓',
    quantity: 25,
    modifiedAt: new Date('2024-04-15'),
  },
  {
    id: '6',
    title: '과학 문제 모음',
    description: '쎈, 마더텅',
    emoji: '👿',
    quantity: 10,
    modifiedAt: new Date('2024-01-15'),
  },
  {
    id: '7',
    title: '23년도 9월차 포엠 수학 재시험',
    description:
      '80점 미만 재시험으로 인해서 집에 가지 못하는 불상사가 발생한 하루이다.',
    emoji: '🤢',
    quantity: 10,
    modifiedAt: new Date('2023-05-31'),
  },
  {
    id: '8',
    title:
      '문제집의 이름을 길게하고 싶은 경우 이런식으로 문제집의 이름을 만들 수 있지않을까?',
    description: '한줄 소개는 이정도로 하자',
    emoji: '💩',
    quantity: 0,
    modifiedAt: new Date('2022-06-07'),
  },
  {
    id: '1',
    title: '23년도 3월 모의고사 오답 모음',
    description: '화이팅 화이팅',
    emoji: '🤓',
    quantity: 25,
    modifiedAt: new Date('2024-04-15'),
  },
  {
    id: '2',
    title: '과학 문제 모음',
    description: '쎈, 마더텅',
    emoji: '👿',
    quantity: 10,
    modifiedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    title: '23년도 9월차 포엠 수학 재시험',
    description:
      '80점 미만 재시험으로 인해서 집에 가지 못하는 불상사가 발생한 하루이다.',
    emoji: '🤢',
    quantity: 10,
    modifiedAt: new Date('2023-05-31'),
  },
  {
    id: '4',
    title:
      '문제집의 이름을 길게하고 싶은 경우 이런식으로 문제집의 이름을 만들 수 있지않을까?',
    description: '한줄 소개는 이정도로 하자',
    emoji: '💩',
    quantity: 0,
    modifiedAt: new Date('2022-06-07'),
  },
  {
    id: '5',
    title: '23년도 3월 모의고사 오답 모음',
    description: '화이팅 화이팅',
    emoji: '🤓',
    quantity: 25,
    modifiedAt: new Date('2024-04-15'),
  },
  {
    id: '6',
    title: '과학 문제 모음',
    description: '쎈, 마더텅',
    emoji: '👿',
    quantity: 10,
    modifiedAt: new Date('2024-01-15'),
  },
  {
    id: '7',
    title: '23년도 9월차 포엠 수학 재시험',
    description:
      '80점 미만 재시험으로 인해서 집에 가지 못하는 불상사가 발생한 하루이다.',
    emoji: '🤢',
    quantity: 10,
    modifiedAt: new Date('2023-05-31'),
  },
  {
    id: '8',
    title:
      '문제집의 이름을 길게하고 싶은 경우 이런식으로 문제집의 이름을 만들 수 있지않을까?',
    description: '한줄 소개는 이정도로 하자',
    emoji: '💩',
    quantity: 0,
    modifiedAt: new Date('2022-06-07'),
  },
];

export const Dummy_Workbook: Workbook = {
  id: '1',
  title:
    '2023 기말고사 대비인데 엄청 길고 길고 긴 제목이라 한 줄에 절대 못담고 적어도 세줄은 되어야할 그런 제목',
  description:
    '2023 포철고 기말고사 대비라서 여기도 진짜 엄청 길게 제목을 담을 꺼야. 그래야 적어도 세줄은 될 거 같애. 아마도 줄바꿈 문자는 안들어갈 것 같은데',
  emoji: '🤓',
  quantity: 23,
  modifiedAt: new Date('2023-09-13'),
};

export const Dummy_Questions: Omit<Question, 'memo'>[] = [
  {
    id: '0',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '1',
    statement:
      'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오. 근데 나는 엄청나게 길고도 긴 문제 예시가 필요해서 지금 그런 걸 만들려고 하는데 혹시 가능할까?',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '2',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '3',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '4',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '5',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '6',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '7',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '8',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '9',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '10',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '11',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '12',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '13',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '14',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '15',
    statement: '이 문제는 어디서부터 건너왔으며 어디서 나온다.',
    options: [
      { value: '원' },
      { value: '삼각형' },
      { value: '직사각형' },
      { value: '오각형' },
    ],
    image: '이상한 url',
    answer: '4',
    category: 'MULTIPLE',
    tags: ['미적분II', '3번틀린문제'],
    modifiedAt: new Date('2023-09-13'),
  },
  {
    id: '16',
    statement: 'cos + sin은 35도일 때 이를 위한 구성요소를 구하시오',
    options: [
      { value: '30' },
      { value: '40' },
      { value: '60' },
      { value: '90' },
    ],
    image: '이상한 url',
    answer: '1',
    category: 'MULTIPLE',
    tags: ['수학II', '이건태그얌'],
    modifiedAt: new Date('2023-09-13'),
  },
];
