import './global.css';
import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import React from 'react';
import AppContainer from '@/app/_components/app-container';
import RQProvider from '@/components/r-q-provider';

const pretendard = localFont({
  src: '../static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: '포테 - 쉽게 문제 정리',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable} bg-outer-bg`}>
      <body className={`${pretendard.className} h-dvh w-dvw`}>
        <RQProvider>
          <AppContainer>{children}</AppContainer>
        </RQProvider>
      </body>
    </html>
  );
}
